export const users = [
  {
    name: 'Admin Manager',
    email: 'admin@example.com',
    password: 'adminpassword123',
    role: 'admin',
    address: {
      street: '100 Tech Park Plaza',
      city: 'San Francisco',
      postalCode: '94107',
      country: 'USA',
      phone: '+1 555-0199',
    },
  },
  {
    name: 'John Doe',
    email: 'user@example.com',
    password: 'userpassword123',
    role: 'user',
    address: {
      street: '456 Innovation Way',
      city: 'Austin',
      postalCode: '78701',
      country: 'USA',
      phone: '+1 555-0142',
    },
  },
];

export const products = [
  {
    name: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones',
    description: 'Industry-leading noise canceling with two processors and 8 microphones. Exceptional sound quality engineered to perfection with the Integrated Processor V1. Crystal clear hands-free calling with 4 beamforming microphones.',
    price: 398.00,
    category: 'Audio',
    brand: 'Sony',
    stock: 24,
    rating: 4.8,
    numReviews: 124,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    featured: true,
    specs: {
      'Battery Life': '30 Hours',
      'Connectivity': 'Bluetooth 5.2',
      'Noise Canceling': 'Active with Dual Processors',
      'Weight': '250g',
    },
  },
  {
    name: 'Apple MacBook Air 13-inch (M3 Chip)',
    description: 'Strikingly thin and fast. The M3 chip brings even greater capabilities to the world’s most popular laptop, with up to 18 hours of battery life and a stunning Liquid Retina display.',
    price: 1099.00,
    category: 'Computers',
    brand: 'Apple',
    stock: 15,
    rating: 4.9,
    numReviews: 89,
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    featured: true,
    specs: {
      'Processor': 'Apple M3 8-core CPU',
      'Memory': '16GB Unified Memory',
      'Storage': '512GB SSD',
      'Display': '13.6-inch Liquid Retina',
    },
  },
  {
    name: 'Logitech MX Master 3S Wireless Performance Mouse',
    description: 'Quiet clicks and 8K DPI track-on-glass sensor. Ergonomic silhouette crafted for the palm of your hand, featuring hyper-fast MagSpeed electromagnetic scrolling.',
    price: 99.99,
    category: 'Accessories',
    brand: 'Logitech',
    stock: 45,
    rating: 4.7,
    numReviews: 215,
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
    featured: false,
    specs: {
      'DPI': '8000 DPI sensor',
      'Battery': 'Up to 70 days rechargeable',
      'Compatibility': 'Windows, macOS, Linux',
    },
  },
  {
    name: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
    description: 'Full aluminum 75% layout mechanical keyboard with hot-swappable switches, double-gasket design, QMK/VIA support, and Bluetooth 5.1 wireless connectivity.',
    price: 199.00,
    category: 'Accessories',
    brand: 'Keychron',
    stock: 8,
    rating: 4.9,
    numReviews: 76,
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    featured: true,
    specs: {
      'Switches': 'Gateron Jupiter Brown',
      'Connectivity': 'Bluetooth 5.1 & Type-C',
      'Case Material': 'CNC Machined Aluminum',
    },
  },
  {
    name: 'Apple Watch Series 9 GPS 45mm',
    description: 'Powerful health sensor suite with Blood Oxygen, ECG, and Temperature sensing. Features the brilliant Always-On Retina display with up to 2000 nits and revolutionary Double Tap gesture.',
    price: 429.00,
    category: 'Wearables',
    brand: 'Apple',
    stock: 12,
    rating: 4.8,
    numReviews: 142,
    imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80',
    featured: true,
    specs: {
      'Case Size': '45mm Aluminum',
      'Water Resistance': '50 meters',
      'Chip': 'S9 SiP with 64-bit dual-core',
    },
  },
  {
    name: 'Bose SoundLink Revolve+ II Bluetooth Speaker',
    description: 'Delivers true 360-degree sound for consistent, uniform coverage. Durable, water- and dust-resistant design (IP55) with flexible fabric handle and up to 17 hours of battery life.',
    price: 299.00,
    category: 'Audio',
    brand: 'Bose',
    stock: 18,
    rating: 4.6,
    numReviews: 67,
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    featured: false,
    specs: {
      'Sound': 'True 360-degree acoustic deflector',
      'Battery': 'Up to 17 hours',
      'Durability': 'IP55 water/dust resistant',
    },
  },
  {
    name: 'Sony PlayStation 5 DualSense Wireless Controller',
    description: 'Heighten your gaming senses with immersive haptic feedback, dynamic adaptive triggers, and a built-in microphone, all integrated into an iconic ergonomic design.',
    price: 69.99,
    category: 'Gaming',
    brand: 'Sony',
    stock: 35,
    rating: 4.8,
    numReviews: 310,
    imageUrl: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=800&q=80',
    featured: false,
    specs: {
      'Feedback': 'Haptic vibration & adaptive triggers',
      'Battery': 'Rechargeable USB-C',
      'Motion': '6-axis motion sensing system',
    },
  },
  {
    name: 'Samsung 32-inch Odyssey Neo G8 4K Curved Gaming Monitor',
    description: 'Quantum Mini-LED display with 240Hz refresh rate and 1ms response time. 1000R curvature matches the human field of view for unprecedented realism and eye comfort.',
    price: 999.99,
    category: 'Computers',
    brand: 'Samsung',
    stock: 4, // Low stock on purpose for testing inventory alert!
    rating: 4.7,
    numReviews: 48,
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    featured: true,
    specs: {
      'Resolution': '3840 x 2160 (4K UHD)',
      'Refresh Rate': '240Hz',
      'Panel': 'Quantum Mini-LED Curved',
    },
  },
  {
    name: 'Anker 737 Power Bank (PowerCore 24K)',
    description: 'Ultra-powerful 140W two-way fast charging with smart digital display. Equipped with 24,000mAh capacity capable of charging a MacBook Pro 16" to 50% in just 40 minutes.',
    price: 139.99,
    category: 'Accessories',
    brand: 'Anker',
    stock: 30,
    rating: 4.8,
    numReviews: 180,
    imageUrl: 'https://images.unsplash.com/photo-1609592424364-41133379be2a?auto=format&fit=crop&w=800&q=80',
    featured: false,
    specs: {
      'Capacity': '24,000 mAh',
      'Max Output': '140W USB-C PD 3.1',
      'Display': 'Real-time smart screen',
    },
  },
  {
    name: 'Kindle Paperwhite (16 GB) - 6.8" Glare-Free Display',
    description: 'Purpose-built for reading with a flush-front design and 300 ppi glare-free display that reads like real paper, even in bright sunlight. Adjustable warm light and up to 10 weeks of battery life.',
    price: 149.99,
    category: 'Wearables',
    brand: 'Amazon',
    stock: 3, // Low stock for alert test
    rating: 4.8,
    numReviews: 320,
    imageUrl: 'https://images.unsplash.com/photo-1592496001020-d31bd830651f?auto=format&fit=crop&w=800&q=80',
    featured: false,
    specs: {
      'Display': '6.8-inch Paperwhite 300 ppi',
      'Battery': 'Up to 10 weeks',
      'Waterproof': 'IPX8 rated',
    },
  },
  {
    name: 'Smart WiFi LED Ambient Desk Lamp',
    description: 'Modern minimalist design with full RGB color spectrum, tunable white temperatures (2700K - 6500K), app control, and sync with music rhythm.',
    price: 49.99,
    category: 'Home',
    brand: 'Lumino',
    stock: 22,
    rating: 4.5,
    numReviews: 62,
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
    featured: false,
    specs: {
      'Color Temperature': '2700K - 6500K RGBW',
      'Connectivity': 'WiFi 2.4GHz & Bluetooth',
      'Voice Assistant': 'Alexa & Google Assistant Compatible',
    },
  },
  {
    name: 'Ember Temperature Control Smart Mug 2',
    description: 'Designed for home or office, Ember Mug 2 allows you to set your precise drinking temperature and keeps it there for up to 80 minutes, or all day on the charging coaster.',
    price: 129.95,
    category: 'Home',
    brand: 'Ember',
    stock: 14,
    rating: 4.4,
    numReviews: 53,
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    featured: false,
    specs: {
      'Capacity': '10 oz / 295 ml',
      'Temperature Range': '120°F - 145°F (50°C - 62.5°C)',
      'Battery': '80 mins on battery, all-day on coaster',
    },
  }
];
